#!/bin/bash
#
#   this scrtips install Hashicorp's Consul on a Debian GNU/Linux based system
#

# check if is Linux
[[ "$( uname --operating-system )" != "GNU/Linux" ]] && echo 'GNU/Linux only!' && exit 3

# check if is Debian
[[ ! -f /etc/debian_version ]] && echo 'Debian only!' && exit 2

# variables
INST_DIR="/usr/local/bin"
PROG_BIN="consul"

PROG_CFG="/etc/${PROG_BIN}.d"
PROG_DFL="/etc/default/${PROG_BIN}"
PROG_ERR="/var/log/${PROG_BIN}.error"
PROG_LOG="/var/log/${PROG_BIN}.log"
PROG_SYV="/etc/init.d/consul"
PROG_USR="consul"
PROG_VRS='0.7.0'
PROG_ZIP="${PROG_BIN}.zip"

# check processor architecture
case $( uname --machine | cut --characters=1-3 ) in
    x86)    ARCH='amd64';;
    i68)    ARCH='386';;
    arm)    ARCH='arm';;
    *)      exit 1;;
esac
DOWNLOAD="https://releases.hashicorp.com/consul/0.7.0/consul_${PROG_VRS}_linux_${ARCH}.zip"

# required packages
sudo apt-get install --yes unzip wget

# download consul and install on right place
cd /tmp/
wget --no-verbose --output-document=${PROG_ZIP} ${DOWNLOAD}
unzip ${PROG_ZIP}
sudo chmod +x consul
sudo mv consul ${INST_DIR}/${PROG_BIN}

# create a new user
HOME_DIR="/var/lib/${PROG_BIN}"
sudo adduser --system --home ${HOME_DIR} --group --disabled-password --disabled-login ${PROG_USR}

# create configuration directory
sudo mkdir ${PROG_CFG}
sudo chown root.${PROG_USR} ${PROG_CFG}
sudo chmod 755 ${PROG_CFG}

# create a default configuration file
sudo cp /vagrant/scripts/consul_default ${PROG_DFL}

# create log files
sudo touch ${PROG_ERR} ${PROG_LOG}
sudo chown root.${PROG_USR} ${PROG_ERR} ${PROG_LOG}
sudo chmod 664 ${PROG_ERR} ${PROG_LOG}

# copy startup scripst and enable at boot
sudo cp /vagrant/scripts/consul ${PROG_SYV}
sudo chmod 755 ${PROG_SYV}
sudo update-rc.d ${PROG_BIN} defaults

exit 0
